baseURL = 'https://Gershon779.github.io/'
languageCode = 'zh-cn'
title = 'Gershon 的博客'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "你好 👋", Content = "欢迎来到 Gershon 的个人博客！" }

  # 网站图标设置
  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon.ico"
    favicon32x32 = "favicon.ico"
    apple_touch_icon = "favicon.ico"